name: lanio_la5r_controller
description: An implementation of LA-5T2S controller
version: 1.0.1
repository: https://github.com/espresso3389/lanio_la5r_controller

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  synchronized: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
